version: '3.7'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password

  web:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - elixir_deps:/app/deps
    ports:
      - '4000:4000'
    restart: always
    depends_on:
      - db
    command: ./.docker/app/run.sh
    secrets:
      - pg_password

secrets:
  pg_password:
    file: ./.docker/secrets/pg_password.txt

volumes:
  pgdata:
  node_modules:
  elixir_deps:
