version: '3.7'
services:
  web:
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: .docker/app/run.sh -d
    # Add port for LogViewer
    ports:
      - 5900:5900

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
